### 좋아요 생성
POST /localhost:8080/posts/1/likes?createdBy=harris
Content-Type: application/json

### 좋아요 수정
PUT /localhost:8080/comments/1
Content-Type: application/json

{
    "content" : "수정된 댓글 내용",
    "updateddBy" : "댓글 작성자"
}

### 좋아요 삭제
DELETE /localhost:8080/comments/1?deletedBy=댓글삭제자
